<script>
	export let title;
</script>

<h1 class="tracking-in-expand">{title}</h1>

<style>
	h1 {
		text-align: center;
		font-weight: 600;
		font-size: 3rem;
	}

	.tracking-in-expand {
		-webkit-animation: tracking-in-expand 0.4s cubic-bezier(0.215, 0.61, 0.355, 1) both;
		animation: tracking-in-expand 0.4s cubic-bezier(0.215, 0.61, 0.355, 1) both;
	}

	/* ----------------------------------------------
    * Generated by Animista on 2021-12-17 21:8:20
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

	/**
    * ----------------------------------------
    * animation tracking-in-expand
    * ----------------------------------------
    */
	@-webkit-keyframes tracking-in-expand {
		0% {
			letter-spacing: -0.5em;
			opacity: 0;
		}
		40% {
			opacity: 0.6;
		}
		100% {
			opacity: 1;
		}
	}
	@keyframes tracking-in-expand {
		0% {
			letter-spacing: -0.5em;
			opacity: 0;
		}
		40% {
			opacity: 0.6;
		}
		100% {
			opacity: 1;
		}
	}
</style>
